import type { Job } from "@/types/job";
import { trustedCompanies } from "@/lib/source-registry";

function daysFromNow(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}

function daysAgo(days: number) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString().slice(0, 10);
}

const companyById = new Map(trustedCompanies.map((company) => [company.id, company]));

function job(input: Omit<Job, "company" | "companyLogo" | "companySlug" | "sourceDomain" | "verified" | "verificationStatus" | "lastCheckedAt">): Job {
  const company = companyById.get(input.companyId);
  if (!company) throw new Error(`Unknown company: ${input.companyId}`);

  return {
    ...input,
    company: company.name,
    companyLogo: company.logo,
    companySlug: company.slug,
    sourceDomain: company.domain,
    verified: true,
    verificationStatus: "verified",
    lastCheckedAt: new Date().toISOString()
  };
}

export const seedJobs: Job[] = [
  job({
    id: "job-tcs-fresher-engineer",
    title: "Fresher Software Engineer Program",
    companyId: "company-tcs",
    sourceUrl: "https://www.tcs.com/careers",
    officialApplyUrl: "https://www.tcs.com/careers",
    location: "Pan India",
    country: "India",
    skills: ["Java", "SQL", "Problem solving", "Communication"],
    eligibility: "Final year and recent graduates should verify eligibility on the official TCS careers page before applying.",
    deadline: daysFromNow(5),
    openedAt: daysAgo(2),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT"],
    remote: false,
    fresher: true,
    confidenceScore: 94,
    aiSummary: "Good fresher-friendly technology opportunity. Check the official TCS careers page for batch, degree, and test details before submitting.",
    priorityScore: 96
  }),
  job({
    id: "job-infosys-systems-associate",
    title: "Systems Associate - Entry Level",
    companyId: "company-infosys",
    sourceUrl: "https://www.infosys.com/careers/",
    officialApplyUrl: "https://www.infosys.com/careers/",
    location: "Bengaluru, Pune, Hyderabad",
    country: "India",
    skills: ["Programming fundamentals", "Aptitude", "SDLC", "Teamwork"],
    eligibility: "Entry-level applicants should confirm eligible branches, graduation year, and selection steps on Infosys Careers.",
    deadline: daysFromNow(12),
    openedAt: daysAgo(4),
    jobType: "IT",
    categories: ["Private", "Freshers", "IT"],
    remote: false,
    fresher: true,
    confidenceScore: 92,
    aiSummary: "Suitable for students seeking an IT services role. The official careers page is the only apply route shown here.",
    priorityScore: 88
  }),
  job({
    id: "job-microsoft-internship",
    title: "Software Engineering Internship",
    companyId: "company-microsoft",
    sourceUrl: "https://jobs.careers.microsoft.com/global/en/search",
    officialApplyUrl: "https://jobs.careers.microsoft.com/global/en/search",
    location: "Hyderabad / Bengaluru",
    country: "India",
    salaryMin: 0,
    currency: "INR",
    skills: ["Data structures", "Algorithms", "Cloud", "TypeScript"],
    eligibility: "Students enrolled in a relevant degree should verify graduation timelines and location requirements on Microsoft Careers.",
    deadline: daysFromNow(3),
    openedAt: daysAgo(1),
    jobType: "Internship",
    categories: ["Internship", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 96,
    aiSummary: "High-trust internship listing source. Apply only after confirming exact role ID and eligibility on Microsoft Careers.",
    priorityScore: 99
  }),
  job({
    id: "job-google-cloud-resident",
    title: "Cloud Technical Resident",
    companyId: "company-google",
    sourceUrl: "https://www.google.com/about/careers/applications/jobs/results/",
    officialApplyUrl: "https://www.google.com/about/careers/applications/jobs/results/",
    location: "Bengaluru / Gurgaon",
    country: "India",
    skills: ["Cloud computing", "Linux", "Networking", "Customer empathy"],
    eligibility: "Early-career candidates should check degree, experience, and location requirements on Google Careers.",
    deadline: daysFromNow(18),
    openedAt: daysAgo(6),
    jobType: "IT",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 95,
    aiSummary: "Strong early-career cloud pathway. Read the official job page carefully for role ID, travel, and work authorization details.",
    priorityScore: 84
  }),
  job({
    id: "job-accenture-associate-software-engineer",
    title: "Associate Software Engineer - Fresher",
    companyId: "company-accenture",
    sourceUrl: "https://www.accenture.com/in-en/careers",
    officialApplyUrl: "https://www.accenture.com/in-en/careers",
    location: "Bengaluru, Hyderabad, Pune, Chennai",
    country: "India",
    skills: ["Programming fundamentals", "Cloud basics", "SQL", "Communication"],
    eligibility: "Students and graduates should confirm batch, degree, assessment, and location rules on Accenture Careers before applying.",
    deadline: daysFromNow(4),
    openedAt: daysAgo(1),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 94,
    aiSummary: "Fresher-friendly technology role source from Accenture's official careers portal. Verify the exact job ID and eligibility before submitting.",
    priorityScore: 98
  }),
  job({
    id: "job-wipro-project-engineer",
    title: "Project Engineer - Entry Level",
    companyId: "company-wipro",
    sourceUrl: "https://careers.wipro.com/",
    officialApplyUrl: "https://careers.wipro.com/",
    location: "Pan India",
    country: "India",
    skills: ["Java", "Aptitude", "SDLC", "Team collaboration"],
    eligibility: "Fresh graduates should check eligible branches, pass-out year, service agreement, and selection process on Wipro Careers.",
    deadline: daysFromNow(8),
    openedAt: daysAgo(2),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT"],
    remote: false,
    fresher: true,
    confidenceScore: 91,
    aiSummary: "Official Wipro career source suitable for entry-level IT job seekers. Use the company portal only and review the role notice carefully.",
    priorityScore: 90
  }),
  job({
    id: "job-hcltech-graduate-engineer-trainee",
    title: "Graduate Engineer Trainee",
    companyId: "company-hcltech",
    sourceUrl: "https://www.hcltech.com/careers",
    officialApplyUrl: "https://www.hcltech.com/careers",
    location: "Noida, Chennai, Bengaluru",
    country: "India",
    skills: ["Networking basics", "Linux", "Cloud support", "Troubleshooting"],
    eligibility: "Applicants should verify degree, graduation year, shifts, and work location on the HCLTech careers page.",
    deadline: daysFromNow(13),
    openedAt: daysAgo(1),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT"],
    remote: false,
    fresher: true,
    confidenceScore: 90,
    aiSummary: "Good IT services pathway for students interested in infrastructure, support, and engineering roles from HCLTech's official source.",
    priorityScore: 87
  }),
  job({
    id: "job-ibm-associate-system-engineer",
    title: "Associate System Engineer",
    companyId: "company-ibm",
    sourceUrl: "https://www.ibm.com/careers/search",
    officialApplyUrl: "https://www.ibm.com/careers/search",
    location: "Bengaluru, Hyderabad, Pune",
    country: "India",
    skills: ["Java", "Cloud", "Problem solving", "Agile"],
    eligibility: "Early-career applicants should confirm job requisition, degree, experience range, and location on IBM Careers.",
    deadline: daysFromNow(16),
    openedAt: daysAgo(3),
    jobType: "IT",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 93,
    aiSummary: "Official IBM career source for entry-level technology roles. Confirm exact requisition details before applying.",
    priorityScore: 86
  }),
  job({
    id: "job-amazon-student-programs-internship",
    title: "Student Programs Internship",
    companyId: "company-amazon",
    sourceUrl: "https://www.amazon.jobs/",
    officialApplyUrl: "https://www.amazon.jobs/",
    location: "Bengaluru, Chennai, Hyderabad",
    country: "India",
    skills: ["Data structures", "Algorithms", "Ownership", "Debugging"],
    eligibility: "Students should search the official Amazon Jobs student programs portal and confirm graduation timeline, role ID, and location.",
    deadline: daysFromNow(6),
    openedAt: daysAgo(0),
    jobType: "Internship",
    categories: ["Internship", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 95,
    aiSummary: "High-trust internship source from Amazon's official jobs portal. Check exact student program listings before submitting.",
    priorityScore: 97
  }),
  job({
    id: "job-deloitte-analyst-trainee",
    title: "Analyst Trainee - Technology",
    companyId: "company-deloitte",
    sourceUrl: "https://www2.deloitte.com/global/en/careers/job-search.html",
    officialApplyUrl: "https://www2.deloitte.com/global/en/careers/job-search.html",
    location: "Hyderabad, Bengaluru, Gurugram",
    country: "India",
    skills: ["Business analysis", "SQL", "Excel", "Client communication"],
    eligibility: "Students should verify degree, graduation year, assessment, and office location on Deloitte's official job search page.",
    deadline: daysFromNow(10),
    openedAt: daysAgo(2),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 91,
    aiSummary: "Official Deloitte career source for student-friendly analyst and technology opportunities. Confirm all eligibility details on the source page.",
    priorityScore: 89
  }),
  job({
    id: "job-capgemini-graduate-analyst",
    title: "Graduate Analyst - Digital and Cloud",
    companyId: "company-capgemini",
    sourceUrl: "https://www.capgemini.com/careers/",
    officialApplyUrl: "https://www.capgemini.com/careers/",
    location: "Mumbai, Pune, Kolkata, Bengaluru",
    country: "India",
    skills: ["Cloud fundamentals", "Testing", "JavaScript", "Consulting mindset"],
    eligibility: "Freshers should verify batch, academic criteria, selection steps, and business unit details on Capgemini Careers.",
    deadline: daysFromNow(15),
    openedAt: daysAgo(4),
    jobType: "Freshers",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 90,
    aiSummary: "Official Capgemini source for graduate technology roles. Students should inspect the final job post before applying.",
    priorityScore: 84
  }),
  job({
    id: "job-oracle-cloud-engineer-entry",
    title: "Cloud Engineer - Early Career",
    companyId: "company-oracle",
    sourceUrl: "https://www.oracle.com/careers/",
    officialApplyUrl: "https://www.oracle.com/careers/",
    location: "Bengaluru / Hyderabad",
    country: "India",
    skills: ["Databases", "Cloud", "Linux", "APIs"],
    eligibility: "Candidates should verify experience level, degree, job ID, and work location on Oracle Careers.",
    deadline: daysFromNow(20),
    openedAt: daysAgo(5),
    jobType: "IT",
    categories: ["Private", "Freshers", "IT", "International"],
    remote: false,
    fresher: true,
    confidenceScore: 92,
    aiSummary: "Official Oracle careers source for early-career cloud and software roles. Apply only after confirming the exact posting.",
    priorityScore: 82
  }),
  job({
    id: "job-sbi-junior-associate",
    title: "Junior Associate Recruitment Notice",
    companyId: "company-sbi",
    sourceUrl: "https://sbi.co.in/web/careers",
    officialApplyUrl: "https://sbi.co.in/web/careers",
    location: "India",
    country: "India",
    skills: ["Banking awareness", "Quantitative aptitude", "Reasoning", "Customer service"],
    eligibility: "Applicants must verify age, education, local language, fee, and exam dates on the official SBI careers notice.",
    deadline: daysFromNow(7),
    openedAt: daysAgo(3),
    jobType: "Banking",
    categories: ["Government", "Banking", "Freshers"],
    remote: false,
    fresher: true,
    confidenceScore: 93,
    aiSummary: "Official public-sector banking opportunity source. Use only the SBI Careers portal and read the notification PDF before paying any fee.",
    priorityScore: 97
  }),
  job({
    id: "job-upsc-recruitment",
    title: "Government Recruitment Notification",
    companyId: "company-upsc",
    sourceUrl: "https://upsc.gov.in/recruitment",
    officialApplyUrl: "https://upsc.gov.in/recruitment",
    location: "India",
    country: "India",
    skills: ["General studies", "Subject knowledge", "Document verification"],
    eligibility: "Check the exact post notification, age limits, education, reservation rules, and closing date on UPSC before applying.",
    deadline: daysFromNow(6),
    openedAt: daysAgo(5),
    jobType: "Government",
    categories: ["Government"],
    remote: false,
    fresher: false,
    confidenceScore: 91,
    aiSummary: "Official government recruitment source. Students should confirm the exact notification number and eligibility on UPSC.",
    priorityScore: 95
  }),
  job({
    id: "job-rbi-assistant-recruitment",
    title: "Assistant Recruitment Notice",
    companyId: "company-rbi",
    sourceUrl: "https://www.rbi.org.in/Scripts/bs_viewcontent.aspx?Id=3580",
    officialApplyUrl: "https://www.rbi.org.in/Scripts/bs_viewcontent.aspx?Id=3580",
    location: "India",
    country: "India",
    skills: ["Banking awareness", "Reasoning", "English", "Quantitative aptitude"],
    eligibility: "Applicants must confirm official notification number, age limits, education, exam pattern, fee, and closing date on RBI.",
    deadline: daysFromNow(2),
    openedAt: daysAgo(1),
    jobType: "Banking",
    categories: ["Government", "Banking", "Freshers"],
    remote: false,
    fresher: true,
    confidenceScore: 94,
    aiSummary: "Official RBI recruitment source with high deadline priority. Read the notification carefully and avoid third-party payment links.",
    priorityScore: 100
  }),
  job({
    id: "job-isro-scientist-engineer-recruitment",
    title: "Scientist / Engineer Recruitment Source",
    companyId: "company-isro",
    sourceUrl: "https://www.isro.gov.in/Careers.html",
    officialApplyUrl: "https://www.isro.gov.in/Careers.html",
    location: "India",
    country: "India",
    skills: ["Engineering fundamentals", "Aptitude", "Technical subject", "Document verification"],
    eligibility: "Students should verify discipline, degree percentage, age, category rules, and center-wise vacancy details on ISRO Careers.",
    deadline: daysFromNow(11),
    openedAt: daysAgo(2),
    jobType: "Government",
    categories: ["Government", "IT"],
    remote: false,
    fresher: true,
    confidenceScore: 92,
    aiSummary: "Official ISRO careers source for technical government opportunities. Confirm the exact advertisement before applying.",
    priorityScore: 91
  })
];

export const categorySlugs = [
  { slug: "government-jobs", label: "Government Jobs", category: "Government" },
  { slug: "private-jobs", label: "Private Jobs", category: "Private" },
  { slug: "internship", label: "Internship", category: "Internship" },
  { slug: "remote-jobs", label: "Remote Jobs", category: "Remote" },
  { slug: "banking", label: "Banking", category: "Banking" },
  { slug: "railway", label: "Railway", category: "Railway" },
  { slug: "it-companies", label: "IT Companies", category: "IT" },
  { slug: "teaching-jobs", label: "Teaching Jobs", category: "Teaching" },
  { slug: "abroad-jobs", label: "Abroad Jobs", category: "International" }
] as const;
